(in-package :cl-events)

(defclass chained-executor ()
  ()
  (:documentation "Emulates serial-executor for non-blocking environments"))

(defmethod invoke-event-handlers ((event chained-executor) &rest args)
  (let ((handlers (event-handlers-list event))
        (handler-index 0))
    (labels ((execute-handler ()
               (apply (aref handlers handler-index) args))
             (next()
               (when (< handler-index (length handlers))
                 (bb:create-promise
                  (lambda (resolve reject)
                    (declare (ignore reject))
                    (bb:attach (execute-handler)
                            (lambda (&rest args)
                              (declare (ignore args))
                              (incf handler-index)
                              (bb:attach (next)
                                         (lambda (&rest args)
                                           (declare (ignore args))
                                           (funcall resolve))))))))))
      (next))))
